name: Build Program

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Build and Execute
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "29.4"

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.92.0

      - name: Setup gcc
        run: |
          sudo apt-get update -y
          sudo apt install -y gcc-riscv64-linux-gnu
          rustup target add riscv64gc-unknown-linux-gnu

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up -v 6.0.0-beta.1
          ~/.sp1/bin/cargo-prove prove --version

      - name: Build SP1 program
        run: |
          cd program
          ~/.sp1/bin/cargo-prove prove build

      - name: Execute SP1 program
        run: |
          cargo run --release -- --minimal-execute
